/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2020-09-16 12:48:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/localProject/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp2/wtpwebapps/project/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1598526168805L));
    _jspx_dependants.put("jar:file:/D:/localProject/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp2/wtpwebapps/project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/jsp/../include/include.jsp", Long.valueOf(1600257781627L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html> \r\n");
      out.write("<html> \r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\r<!-- for jQuery -->\r<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/jquery/jquery.min.js\"></script>\r<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.serialize-object.js\"></script>\r<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\r<!-- Bootstrap core CSS -->\r<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\r<!-- Custom styles for this template -->\r<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/simple-sidebar.css\" rel=\"stylesheet\">\r\r<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/semantic.min.css\" rel=\"stylesheet\">\r\r");
      out.write("\r \r<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/font-awesome.min.css\" rel=\"stylesheet\">\r<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/ionicons.min.css\" rel=\"stylesheet\">\r\r\r\r<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/semantic.min.js\"></script>");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<title>Profile</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body {\r\n");
      out.write("    font-family: 'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif;\r\n");
      out.write("    font-weight: 400;\r\n");
      out.write("    overflow-x: hidden;\r\n");
      out.write("}\r\n");
      out.write(".table{\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write(".table,td{\r\n");
      out.write("\tborder:1px solid #dee2e6;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"d-flex\" id=\"wrapper\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "template/sidebar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"page-content-wrapper\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "template/header.jsp", out, false);
      out.write("\r\n");
      out.write("<div class=\"container-fluid\" style=\"height:84%;\">\r\n");
      out.write("    \r\n");
      out.write("<!-- Page Content Start -->\r\n");
      out.write("\r\n");
      out.write("<div id=\"profilePage\" style=\"min-width:1200px; min-height:638px;\">\r\n");
      out.write("\t<div class=\"mt-4\">\r\n");
      out.write("\t\t<h3>기본 정보</h3>\r\n");
      out.write("\t</div>\r\n");
      out.write("  <!-- /.box-header -->\r\n");
      out.write("\t<div class=\"mt-3\" style=\"margin-left:15px;margin-right:15px;border-top:1px solid #dee2e6;\">\r\n");
      out.write("\t<form name=\"userParamForm1\" id=\"userParamForm1\" role=\"form\">\r\n");
      out.write("\t<input type=\"hidden\" id=\"p_id\" name=\"p_id\">\r\n");
      out.write("\t<input type=\"hidden\" id=\"p_birth\" name=\"p_birth\">\r\n");
      out.write("\t<input type=\"hidden\" id=\"p_phone\" name=\"p_phone\">\r\n");
      out.write("\t<input type=\"hidden\" id=\"p_mail\" name=\"p_mail\">\r\n");
      out.write("\t<table class=\"table table-striped\">\r\n");
      out.write("\t  <colgroup>\r\n");
      out.write("\t\t<col width=\"10%\"/>\r\n");
      out.write("\t\t<col width=\"90%\"/>\r\n");
      out.write("\t  </colgroup>\r\n");
      out.write("\t  <tr>\r\n");
      out.write("\t    <td>아이디</td>\r\n");
      out.write("\t    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t  </tr>\r\n");
      out.write("\t  <tr>\r\n");
      out.write("\t    <td>비밀번호</td>\r\n");
      out.write("\t    <td><input type=\"password\" name=\"u_pw\" style=\"border:1px solid #dee2e6;\"></td>\r\n");
      out.write("\t  </tr>\r\n");
      out.write("\t  <tr>\r\n");
      out.write("\t    <td>비밀번호 확인</td>\r\n");
      out.write("\t    <td><input type=\"password\" name=\"u_pw2\" style=\"border:1px solid #dee2e6;\"></td>\r\n");
      out.write("\t  </tr>\r\n");
      out.write("\t  <tr>\r\n");
      out.write("\t    <td>이름</td>\r\n");
      out.write("\t    <td><input type=\"text\" name=\"u_name\" style=\"border:1px solid #dee2e6;\"></td>\r\n");
      out.write("\t  </tr>\r\n");
      out.write("\t  <tr>\r\n");
      out.write("\t    <td>휴대폰 번호</td>\r\n");
      out.write("\t    <td><select id=\"u_phone1\" name=\"u_phone1\" style=\"border:1px solid #dee2e6;height: 24.8px;width:80px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>010</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>011</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>016</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>017</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option>019</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t<label style=\"font-size: 15px;line-height: 1.0;\">-</label>\t\t\t\t\t\t\r\n");
      out.write("\t    <input type=\"text\" name=\"u_phone2\" maxlength=\"4\" style=\"border:1px solid #dee2e6;width:80px;\">\r\n");
      out.write("\t    <label style=\"font-size: 15px;line-height: 1.0;\">-</label>\r\n");
      out.write("\t    <input type=\"text\" name=\"u_phone3\" maxlength=\"4\" style=\"border:1px solid #dee2e6;width:80px;\">\r\n");
      out.write("\t  </tr>\r\n");
      out.write("\t  <tr>\r\n");
      out.write("\t    <td>이메일</td>\r\n");
      out.write("\t    <td><input type=\"text\" name=\"mail_name\" maxlength=\"50\" style=\"border:1px solid #dee2e6;\">\r\n");
      out.write("            <label style=\"font-size: 15px;line-height: 1.0;\">@</label>\r\n");
      out.write("\t\t\t<select id=\"mail_addr\" name=\"mail_addr\" style=\"border:1px solid #dee2e6;height: 27.5px; width:150px;\">\r\n");
      out.write("\t\t\t\t<option>naver.com</option>\r\n");
      out.write("\t\t\t\t<option>daum.net</option>\r\n");
      out.write("\t\t\t\t<option>gmail.com</option>\r\n");
      out.write("\t\t\t\t<option>nate.com</option>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t    </td>\r\n");
      out.write("\t  </tr>\r\n");
      out.write("\t  <tr>\r\n");
      out.write("\t    <td>주소</td>\r\n");
      out.write("\t    <td><input type=\"text\" name=\"u_addr\" style=\"border:1px solid #dee2e6; width:50%;\"></td>\r\n");
      out.write("\t  </tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("  <!-- /.box-body -->\r\n");
      out.write("\t<div class=\"mt-4\">\r\n");
      out.write("\t\t<h3>추가 정보</h3>\r\n");
      out.write("\t</div>\r\n");
      out.write("  <!-- /.box-header -->\r\n");
      out.write("\t<div class=\"mt-3\" style=\"margin-left:15px;margin-right:15px;border-top:1px solid #dee2e6;\">\r\n");
      out.write("\t<form name=\"userParamForm2\" id=\"userParamForm2\" role=\"form\">\r\n");
      out.write("\t<table class=\"table table-striped\">\r\n");
      out.write("\t  <colgroup>\r\n");
      out.write("\t\t<col width=\"10%\"/>\r\n");
      out.write("\t\t<col width=\"90%\"/>\r\n");
      out.write("\t  </colgroup>\r\n");
      out.write("\t  <tr>\r\n");
      out.write("\t    <td>성별</td>\r\n");
      out.write("\t    <td><input type=\"radio\" name=\"gender\" value = \"M\" style=\"margin-right:10px; float:left; margin-left:10px; margin-top:3px\" checked id = \"r1\" >\r\n");
      out.write("            <label for = \"r1\" style=\"float:left;\">남자</label>\r\n");
      out.write("            <input type=\"radio\" name=\"gender\" value = \"F\" style=\"margin-right: 10px; float:left; margin-left:20px; margin-top:3px\" id = \"r2\">\r\n");
      out.write("            <label for = \"r2\" style=\"float:left;\">여자</label>\r\n");
      out.write("\t    </td>\r\n");
      out.write("\t  </tr>\r\n");
      out.write("\t  <tr>\r\n");
      out.write("\t    <td>생년월일</td>\r\n");
      out.write("\t    <td><input type=\"text\" name=\"birthyy\" maxlength=\"4\" style=\"float:left; border:1px solid #dee2e6; width:80px; margin-right: 5px; font-size: 13px;\">\r\n");
      out.write("\t\t\t<label for = \"r1\" style=\"float:left; margin-right:5px;\">년</label>\r\n");
      out.write("\t\t\t<select id=\"birthmm\" name=\"birthmm\" style=\"float:left; border:1px solid #dee2e6; width:80px; margin-right: 5px; font-size: 13px; height: 27.5px;\">\r\n");
      out.write("\t\t\t\t<option value=\"01\" >01</option>\r\n");
      out.write("\t\t\t\t<option value=\"02\" >02</option>\r\n");
      out.write("\t\t\t\t<option value=\"03\" >03</option>\r\n");
      out.write("\t\t\t\t<option value=\"04\" >04</option>\r\n");
      out.write("\t\t\t\t<option value=\"05\" >05</option>\r\n");
      out.write("\t\t\t\t<option value=\"06\" >06</option>\r\n");
      out.write("\t\t\t\t<option value=\"07\" >07</option>\r\n");
      out.write("\t\t\t\t<option value=\"08\" >08</option>\r\n");
      out.write("\t\t\t\t<option value=\"09\" >09</option>\r\n");
      out.write("\t\t\t\t<option value=\"10\" >10</option>\r\n");
      out.write("\t\t\t\t<option value=\"11\" >11</option>\r\n");
      out.write("\t\t\t\t<option value=\"12\" >12</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t<label for = \"r1\" style=\"float:left;margin-right:5px;\">월</label>\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"birthdd\" maxlength=\"2\" style=\"float:left; border:1px solid #dee2e6; width:80px; margin-right: 5px;font-size: 13px;\">\r\n");
      out.write("\t\t\t<label for = \"r1\" style=\"float:left;\">일</label>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t  </tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("  <!-- /.box-body -->\r\n");
      out.write("  <div style=\"position:relative; left:2%; float:left; width:100%; \">\r\n");
      out.write("  <form name=\"userParamForm3\" id=\"userParamForm3\" role=\"form\">\r\n");
      out.write("      <input type=\"checkbox\" name=\"checkbox\" style=\"margin-top: 15px; font-weight: bold; font-size: 13px;\">\r\n");
      out.write("      <span style=\"position: relative;top: -4px;font-size: 12px;\">개인정보 취급방침에 따른 개인정보의 수집 및 이용에 동의합니다.</span>\r\n");
      out.write("  </form>    \r\n");
      out.write("  </div>\r\n");
      out.write("  <div style=\"position:relative; left:35%; float:left; margin-bottom: 40px;\">\r\n");
      out.write("  <button class=\"btn btn-secondary\" id=\"edit_btn\" style=\"width: 107px;\">회원정보수정</button>\r\n");
      out.write("  <button class=\"btn btn-secondary\" id=\"cancel_btn\" style=\"width: 107px;\">취소</button>\r\n");
      out.write("  <button class=\"btn btn-outline-secondary\" id=\"withdrawal_btn\" style=\"width: 90px; left: 167%; position: relative;\" onclick=\"deleteChkPop()\">회원탈퇴</button>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Page Content End -->\r\n");
      out.write("\r\n");
      out.write("</div>    \r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "template/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("//*********************************************************************************************\r\n");
      out.write("//********** Declare public variable\r\n");
      out.write("//*********************************************************************************************\r\n");
      out.write("var registerChk = 'N';\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("//*********************************************************************************************\r\n");
      out.write("//********** Function Ready Section\r\n");
      out.write("//*********************************************************************************************\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\tinsertInitData();\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#edit_btn\").click(function() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcheckValue();\r\n");
      out.write("\t\tif(registerChk == 'Y'){\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(\"#p_id\").val(u_id);\r\n");
      out.write("\t\t\t$(\"#p_mail\").val(paramMail());\r\n");
      out.write("\t\t\t$(\"#p_phone\").val(paramPhone());\r\n");
      out.write("\t\t\t$(\"#p_birth\").val(paramBirth());\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar paramObj1 = $(\"form[name=userParamForm1]\").serializeObject();\r\n");
      out.write("\t\t\tvar paramObj2 = $(\"form[name=userParamForm2]\").serializeObject();\r\n");
      out.write("\t\t\tvar paramObj3 = $(\"form[name=userParamForm3]\").serializeObject();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar paramObj = Object.assign(paramObj1, paramObj2, paramObj3);\r\n");
      out.write("\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\t\tcontentType: 'application/json',\r\n");
      out.write("\t\t\t\turl : \"editProfile.do\",\r\n");
      out.write("\t\t\t\tdata : JSON.stringify(paramObj),\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\tswitch (Number(data)) {\r\n");
      out.write("\t\t\t\t\tcase 0:\r\n");
      out.write("\t\t\t\t\t\talert(\"변경된 내용이 없습니다.\");\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById('profilePage').style.cssText = 'visibility:hidden;';\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\tcase 1:\r\n");
      out.write("\t\t\t\t\t\talert(\"사용자 정보가 변경되었습니다.\");\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById('profilePage').style.cssText = 'visibility:hidden;';\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\tdefault:\r\n");
      out.write("\t\t\t\t\t\talert(\"알수없는 오류가 발생 했습니다. [Error Code :\" + Number(data) + \"]\");\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(error) {\r\n");
      out.write("\t\t\t\t\talert(\"오류 발생\"+ error);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#cancel_btn\").click(function() {\r\n");
      out.write("\t\tdocument.getElementById('profilePage').style.cssText = 'visibility:hidden;';\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function insertInitData(){\r\n");
      out.write("\t$(\"input[name=u_name]\").val(u_name);\r\n");
      out.write("\t$(\"input[name=u_addr]\").val(u_addr);\r\n");
      out.write("\r\n");
      out.write("\tvar birthyy\t= u_birth.substring(0,4);\r\n");
      out.write("\tvar birthmm = u_birth.substring(4,6);\r\n");
      out.write("\tvar birthdd = u_birth.substring(6,8);\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"input[name=birthyy]\").val(birthyy);\r\n");
      out.write("\t$(\"#birthmm\").val(birthmm);\r\n");
      out.write("\t$(\"input[name=birthdd]\").val(birthdd);\r\n");
      out.write("\t\r\n");
      out.write("\tvar u_phone1 = u_phone.substring(0,3);\r\n");
      out.write("\tvar u_phone2 = u_phone.substring(3,7);\r\n");
      out.write("\tvar u_phone3 = u_phone.substring(7,11);\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#u_phone1\").val(u_phone1);\r\n");
      out.write("\t$(\"input[name=u_phone2]\").val(u_phone2);\r\n");
      out.write("\t$(\"input[name=u_phone3]\").val(u_phone3);\r\n");
      out.write("\t\r\n");
      out.write("\tvar temp_mail = u_email.split('@');\r\n");
      out.write("\tvar mail_name = temp_mail[0];\r\n");
      out.write("\tvar mail_addr = temp_mail[1];\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"input[name=mail_name]\").val(mail_name);\r\n");
      out.write("\t$(\"#mail_addr\").val(mail_addr);\r\n");
      out.write("\t\r\n");
      out.write("\tif(u_gender == 'F'){\r\n");
      out.write("\t\t$('#r2').prop('checked', true);\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t$('#r1').prop('checked', true);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function checkValue(){\r\n");
      out.write("\tvar form1 = document.userParamForm1;\r\n");
      out.write("\tvar form2 = document.userParamForm2;\r\n");
      out.write("\tvar chk = document.userParamForm3.checkbox.checked;\r\n");
      out.write("\t\r\n");
      out.write("\tif(!form1.u_pw.value){\r\n");
      out.write("\t\talert(\"비밀번호를 입력해주세요.\");\r\n");
      out.write("\t\t$(\"input[name=u_pw]\").focus();\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(form1.u_pw.value != form1.u_pw2.value){\r\n");
      out.write("\t\talert(\"비밀번호를 동일하게 입력해주세요.\");\r\n");
      out.write("\t\t$(\"input[name=u_pw2]\").focus();\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(!form1.u_name.value){\r\n");
      out.write("\t\talert(\"이름을 입력해주세요.\");\r\n");
      out.write("\t\t$(\"input[name=u_name]\").focus();\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(!(form1.u_phone2.value)){\r\n");
      out.write("\t\talert(\"전화번호를 입력해주세요.\");\r\n");
      out.write("\t\t$(\"input[name=u_phone2]\").focus();\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(!(form1.u_phone3.value)){\r\n");
      out.write("\t\talert(\"전화번호를 입력해주세요.\");\r\n");
      out.write("\t\t$(\"input[name=u_phone3]\").focus();\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(isNaN(form1.u_phone2.value)){\r\n");
      out.write("\t\talert(\"전화번호는 숫자만 입력가능합니다.\");\r\n");
      out.write("\t\t$(\"input[name=u_phone2]\").focus();\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(isNaN(form1.u_phone3.value)){\r\n");
      out.write("\t\talert(\"전화번호는 숫자만 입력가능합니다.\");\r\n");
      out.write("\t\t$(\"input[name=u_phone3]\").focus();\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(!chk){\r\n");
      out.write("\t\talert(\"개인정보 수집 및 이용에 대한 동의는 필수입니다.\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tregisterChk = 'Y';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function deleteChkPop(){\r\n");
      out.write("\tvar popupWidth = 500;\r\n");
      out.write("\tvar popupHeight = 300;\r\n");
      out.write("\t\r\n");
      out.write("\tvar popupX = (window.screen.width / 2) - (popupWidth / 2);\r\n");
      out.write("\tvar popupY= (window.screen.height / 2) - (popupHeight / 2);\r\n");
      out.write("\t\r\n");
      out.write("\twindow.name = \"parentForm\";\r\n");
      out.write("\twindow.open(\"member/check_delete.do\", \"chkForm\", \"width=\"+ popupWidth +\", height=\"+ popupHeight +\", left=\"+ popupX +\", top=\"+ popupY +\", resizable = no, scrollbars = no\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function paramPhone(){\r\n");
      out.write("\tvar u_phone1= $(\"#u_phone1 option:selected\").val();\r\n");
      out.write("\tvar u_phone2= $(\"input[name=u_phone2]\").val();\r\n");
      out.write("\tvar u_phone3= $(\"input[name=u_phone3]\").val();\r\n");
      out.write("\t\r\n");
      out.write("\treturn u_phone1+u_phone2+u_phone3;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function paramBirth(){\r\n");
      out.write("\tvar birthyy= $(\"input[name=birthyy]\").val();\r\n");
      out.write("\tvar birthmm= $(\"#birthmm option:selected\").val();\r\n");
      out.write("\tvar birthdd= $(\"input[name=birthdd]\").val();\r\n");
      out.write("\t\r\n");
      out.write("\tif(birthdd.length == 1){\r\n");
      out.write("\t\tf_birthdd = '0'+birthdd;\r\n");
      out.write("\t\r\n");
      out.write("\t\treturn birthyy+birthmm+f_birthdd;\r\n");
      out.write("\t}\r\n");
      out.write("\telse{\r\n");
      out.write("\t\treturn birthyy+birthmm+birthdd;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function paramMail(){\r\n");
      out.write("\tvar mail_name= $(\"input[name=mail_name]\").val();\r\n");
      out.write("\tvar mail_addr= $(\"#mail_addr option:selected\").val();\r\n");
      out.write("\t\t\r\n");
      out.write("\treturn mail_name+'@'+mail_addr;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//*********************************************************************************************\r\n");
      out.write("// ********** User Defined Function Section \r\n");
      out.write("//*********************************************************************************************\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/jsp/profile.jsp(56,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty login}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t    <td><span id=\"u_id\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span></td>\r\n");
          out.write("\t    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/jsp/profile.jsp(177,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("item");
      // /WEB-INF/jsp/profile.jsp(177,0) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/profile.jsp(177,0) '${userProfile}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${userProfile}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\tvar u_id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.USER_ID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("\tvar u_name=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.NAME}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("\tvar u_gender=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.GENDER}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("\tvar u_birth=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.BIRTH}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("\tvar u_email=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.EMAIL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("\tvar u_phone=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.PHONE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("\tvar u_addr=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.ADDRESS}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('\r');
            out.write('\n');
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
