/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2020-09-16 13:10:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class timeline_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/localProject/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp2/wtpwebapps/project/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1598526168805L));
    _jspx_dependants.put("jar:file:/D:/localProject/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp2/wtpwebapps/project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/jsp/../include/include.jsp", Long.valueOf(1600257781627L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html> \r\n");
      out.write("<html> \r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\r<!-- for jQuery -->\r<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/jquery/jquery.min.js\"></script>\r<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery.serialize-object.js\"></script>\r<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\r<!-- Bootstrap core CSS -->\r<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/plugins/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\r<!-- Custom styles for this template -->\r<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/simple-sidebar.css\" rel=\"stylesheet\">\r\r<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/semantic.min.css\" rel=\"stylesheet\">\r\r");
      out.write("\r \r<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/font-awesome.min.css\" rel=\"stylesheet\">\r<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/ionicons.min.css\" rel=\"stylesheet\">\r\r\r\r<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/semantic.min.js\"></script>");
      out.write("\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/AdminLTE.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<title>Timeline</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".img-circle{\r\n");
      out.write("\tborder-radius: 50%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"d-flex\" id=\"wrapper\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "template/sidebar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"page-content-wrapper\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "template/header.jsp", out, false);
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!-- Page Content Start -->\r\n");
      out.write("\r\n");
      out.write("<!-- Content Wrapper. Contains page content -->\r\n");
      out.write("  <div class=\"content-wrapper\" style=\"background-color:#ecf0f5; min-width: 1290px; min-height: 780px;\">  \r\n");
      out.write("<!-- Page Content Start -->\r\n");
      out.write("          <!-- Box Comment -->\r\n");
      out.write("         \r\n");
      out.write("          <div class=\"box box-widget\" style=\"margin: 0px;left: 20px;top: 20px;width: 43%;\">\r\n");
      out.write("            <div class=\"box-header with-border\">\r\n");
      out.write("              <div class=\"user-block\">\r\n");
      out.write("                <img class=\"img-circle\" src=\"resources/img/user1-128x128.jpg\" alt=\"User Image\">\r\n");
      out.write("                <span class=\"username\"><a href=\"#\">Jonathan Burke Jr.</a></span>\r\n");
      out.write("                <span class=\"description\">Shared publicly - 7:30 PM Today</span>\r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- /.user-block -->\r\n");
      out.write("              <div class=\"box-tools\">\r\n");
      out.write("<!--                 <button type=\"button\" class=\"btn btn-box-tool\" data-toggle=\"tooltip\" title=\"Mark as read\">\r\n");
      out.write("                  <i class=\"fa fa-circle-o\"></i></button> -->\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-box-tool\" data-toggle=\"collapse\" data-target=\"#zzz\"><i class=\"fa fa-minus\"></i></button>\r\n");
      out.write("<!--                 <button type=\"button\" class=\"btn btn-box-tool\" data-widget=\"remove\" data-target=\"#zzz\"><i class=\"fa fa-times\"></i></button> -->              </div>\r\n");
      out.write("              <!-- /.box-tools -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.box-header -->\r\n");
      out.write("            <div id=\"zzz\" class=\"collapse show box-body\">\r\n");
      out.write("              <img class=\"img-responsive pad\" src=\"resources/img/photo2.png\" alt=\"Photo\" style=\"height: 364px; position: inherit;\">\r\n");
      out.write("\r\n");
      out.write("              <p>I took this photo this morning. What do you guys think?</p>\r\n");
      out.write("              <button type=\"button\" class=\"btn btn-default btn-xs\"><i class=\"fa fa-thumbs-o-up\"></i> Like</button>\r\n");
      out.write("              <span class=\"pull-right text-muted\">127 likes - 3 comments</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.box-body -->\r\n");
      out.write("            <div id=\"zzz\" class=\"collapse show box-footer box-comments\">\r\n");
      out.write("              <div class=\"box-comment\">\r\n");
      out.write("                <!-- User image -->\r\n");
      out.write("                <img class=\"img-circle img-sm\" src=\"resources/img/user3-128x128.jpg\" alt=\"User Image\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"comment-text\">\r\n");
      out.write("                      <span class=\"username\">\r\n");
      out.write("                        Maria Gonzales\r\n");
      out.write("                        <span class=\"text-muted pull-right\">8:03 PM Today</span>\r\n");
      out.write("                      </span><!-- /.username -->\r\n");
      out.write("                  It is a long established fact that a reader will be distracted\r\n");
      out.write("                  by the readable content of a page when looking at its layout.\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- /.comment-text -->\r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- /.box-comment -->\r\n");
      out.write("              <div class=\"box-comment\">\r\n");
      out.write("                <!-- User image -->\r\n");
      out.write("                <img class=\"img-circle img-sm\" src=\"resources/img/user4-128x128.jpg\" alt=\"User Image\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"comment-text\">\r\n");
      out.write("                      <span class=\"username\">\r\n");
      out.write("                        Luna Stark\r\n");
      out.write("                        <span class=\"text-muted pull-right\">8:03 PM Today</span>\r\n");
      out.write("                      </span><!-- /.username -->\r\n");
      out.write("                  It is a long established fact that a reader will be distracted\r\n");
      out.write("                  by the readable content of a page when looking at its layout.\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- /.comment-text -->\r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- /.box-comment -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.box-footer -->\r\n");
      out.write("            <div id=\"zzz\" class=\"collapse show box-footer\">\r\n");
      out.write("              <form action=\"#\" method=\"post\">\r\n");
      out.write("                <img class=\"img-responsive img-circle img-sm\" src=\"resources/img/user4-128x128.jpg\" alt=\"Alt Text\">\r\n");
      out.write("                <!-- .img-push is used to add margin to elements next to floating images -->\r\n");
      out.write("                <div class=\"img-push\">\r\n");
      out.write("                  <input type=\"text\" class=\"form-control input-sm\" placeholder=\"Press enter to post comment\">\r\n");
      out.write("                </div>\r\n");
      out.write("              </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- /.box-footer -->\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- /.box -->\r\n");
      out.write("          \r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- /.content-wrapper -->\r\n");
      out.write("    \r\n");
      out.write("<!-- Page Content End -->\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "template/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
